language: node_js
node_js:
- node
deploy:
  provider: heroku
  api_key:
    secure: YqT83pDXL3lUJx5bjfJT8AW7/6ITIhO7cxeNHBSmuxVnLcwbbxYnSIlvkeNyU7GNRDcj7fwv3fHNcyuOCHWLI665RZeuHoXIg10fmiL3RII8Y8hRZH6FVs8jddsDBY+4Ef4+yf829bktPgrW19LWlikA7TULOKxQGKETFvhTu8FOIHTdRwsqL850qX/J/Nn7PrjsqFTFiW0ZUdWIHDC0QpYa9QspBkHG7ZpAAH3/FyjZKmxQ3Qdl+74P5njjGEvXi1VDaOeuFTzZ+u95JpMCEReeqhUV9hCWzGCj8cfI0vCYSYXCpfbKa+Gl3aeQ0TSoHGhVWGw29nKpzgiw5g7Ez5ppnTOeB8XzqUmYA9tyHYRw772OAKcO1j4LNBz61CGtpeFKJlDcSGzwP+szPVsqozy0lTCc3XkgJcfltRM3X1Oz4FYFABbCFSJ0ct/AlX8VxGJWMbuHYv4WQOMieBaJSHDehzWDgDHVE8OkxOwC1deNoZwD0RqVNqv7H0+Lueqp9CI24MwPmUhcmXEyewFt1wlOTvhEhGzOsfDVmb+b4qa5chyW5bDTIApMZrEiEanwM5GqzG6aLiIEqV/L6vqjzw4T6jpK01eAa+QdUIh9kRjMXiGRFxg7plXYO92aTOjzQEDFswfAb9wYQqnh40CuCIj3WrQZkJkBfbfprMJbwR0=
  app: bibliotec15  
